[package]
name = "test_v1"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.30", features = []}
env_logger = "0.11"
log = "0.4"
wgpu = { version = "24.0" }
pollster = "0.4"
bytemuck = "1.21"
